DJANGO_HYPERCORN_NGINX_EXCHANGE = 'django-hypercorn'

QUEUE_DJANGO_HYPERCORN_NGINX = 'django-hypercorn'
QUEUE_SYSTEM_DJANGO_HYPERCORN_NGINX = 'system-django-hypercorn'

QUEUES_DECLARATION = (
    {
        'exchange': DJANGO_HYPERCORN_NGINX_EXCHANGE,
        'queues': [QUEUE_DJANGO_HYPERCORN_NGINX, QUEUE_SYSTEM_DJANGO_HYPERCORN_NGINX],
    },
)
