DJANGO_HYPERCORN_NGINX_EXCHANGE = 'django_hypercorn_nginx'

QUEUE_DJANGO_HYPERCORN_NGINX = 'django-hypercorn-nginx'
QUEUE_SYSTEM_DJANGO_HYPERCORN_NGINX = 'system-django-hypercorn-nginx'

QUEUES_DECLARATION = (
    {
        'exchange': DJANGO_HYPERCORN_NGINX_EXCHANGE,
        'queues': [QUEUE_DJANGO_HYPERCORN_NGINX, QUEUE_SYSTEM_DJANGO_HYPERCORN_NGINX],
    },
)
